In [ ]:
import numpy as np #numerical python
import pandas as pd #data analysis library

In [ ]:
df = pd.read_csv('examdata.csv')

In [ ]:
df.columns

Index(['overtime_hours', 'monthly_wage'], dtype='object')

In [ ]:
df.dtypes

overtime_hours    float64
monthly_wage      float64
dtype: object

In [ ]:
df.head()

   overtime_hours  monthly_wage
0             5.0        2345.0
1             6.0        2851.0
2             2.0        1412.0
3             NaN        1145.0
4            10.0        2604.0

In [ ]:
len(df)

30

In [ ]:
df.shape

(30, 2)

In [ ]:
df.isnull(). sum()

overtime_hours    4
monthly_wage      4
dtype: int64

In [ ]:
df['overtime_hours'].fillna(df['overtime_hours'].mean(), inplace=True)

<ipython-input-9-c75de083348a>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['overtime_hours'].fillna(df['overtime_hours'].mean(), inplace=True)

In [ ]:
df['overtime_hours'].mean()

6.0

In [ ]:
df.isnull().sum()

overtime_hours    0
monthly_wage      4
dtype: int64

In [ ]:
df['monthly_wage'].fillna(df['monthly_wage'].mean(), inplace=True)

<ipython-input-12-3d89847918f6>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['monthly_wage'].fillna(df['monthly_wage'].mean(), inplace=True)

In [ ]:
df.isnull().sum()

overtime_hours    0
monthly_wage      0
dtype: int64

In [ ]:
df.head(20)

    overtime_hours  monthly_wage
0              5.0   2345.000000
1              6.0   2851.000000
2              2.0   1412.000000
3              6.0   1145.000000
4             10.0   2604.000000
5              3.0   1101.000000
6              4.0   1937.115385
7              7.0   2673.000000
8              9.0   2013.000000
9             12.0   1937.115385
10            15.0   1400.000000
11             3.0   2262.000000
12             5.0   1958.000000
13             6.0   1490.000000
14             7.0   2435.000000
15             8.0   1185.000000
16             9.0   2465.000000
17            11.0   1346.000000
18             6.0   1455.000000
19             3.0   1445.000000

In [ ]:
df.describe()

       overtime_hours  monthly_wage
count       30.000000     30.000000
mean         6.000000   1937.115385
std          3.151354    563.982656
min          1.000000   1101.000000
25%          4.000000   1420.250000
50%          6.000000   1937.115385
75%          7.000000   2363.250000
max         15.000000   2935.000000